/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.EmployeeData;
import model.ProductDetails;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Date;

/**
 *
 * @author sumanayanakonda
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    
    EmployeeData historyArrayList;
    ProductDetails productdetails = new ProductDetails();
    public CreateJPanel(EmployeeData historyArrayList) {
        initComponents();
        this.historyArrayList = historyArrayList;
        jTextName.setName("Name");
        jTextEmployee_ID.setName("Employee_ID");
        jTextGender.setName("Gender");
        jTextLevel.setName("Level");
        jTextTeam_Info.setName("Team_Info");
        jDateChooser.setName("Start_Date");
        jTextEmail_Address.setName("Email");
        jTextAge.setName("Age");
        jTextCell_Phone_Number.setName("Phone_Number");
        jTextPosition_Title.setName("Position_Title");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jTitle = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jEmployee_ID = new javax.swing.JLabel();
        jAge = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jStart_Date = new javax.swing.JLabel();
        jLevel = new javax.swing.JLabel();
        jTeam_Info = new javax.swing.JLabel();
        jPosition_Title = new javax.swing.JLabel();
        jContact_Info = new javax.swing.JLabel();
        jCell_Phone_Number = new javax.swing.JLabel();
        jEmail_Address = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jTextEmployee_ID = new javax.swing.JTextField();
        jTextAge = new javax.swing.JTextField();
        jTextGender = new javax.swing.JTextField();
        jTextLevel = new javax.swing.JTextField();
        jTextTeam_Info = new javax.swing.JTextField();
        jTextPosition_Title = new javax.swing.JTextField();
        jTextCell_Phone_Number = new javax.swing.JTextField();
        jTextEmail_Address = new javax.swing.JTextField();
        jSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jUpload = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Employee ID");

        setBackground(new java.awt.Color(255, 255, 255));

        jTitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("CREATE");
        jTitle.setToolTipText("");

        jName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jName.setText("Name:");

        jEmployee_ID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jEmployee_ID.setText("Employee ID:");

        jAge.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jAge.setText("Age:");

        jGender.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jGender.setText("Gender:");

        jStart_Date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jStart_Date.setText("Start Date:");

        jLevel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLevel.setText("Level:");

        jTeam_Info.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTeam_Info.setText("Team Info:");

        jPosition_Title.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPosition_Title.setText("Position Title:");

        jContact_Info.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jContact_Info.setText("Contact Info:");

        jCell_Phone_Number.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCell_Phone_Number.setText("Phone Number:");

        jEmail_Address.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jEmail_Address.setText("Email Address:");

        jTextName.setBackground(new java.awt.Color(204, 204, 204));
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jTextEmployee_ID.setBackground(new java.awt.Color(204, 204, 204));

        jTextAge.setBackground(new java.awt.Color(204, 204, 204));

        jTextGender.setBackground(new java.awt.Color(204, 204, 204));

        jTextLevel.setBackground(new java.awt.Color(204, 204, 204));

        jTextTeam_Info.setBackground(new java.awt.Color(204, 204, 204));

        jTextPosition_Title.setBackground(new java.awt.Color(204, 204, 204));
        jTextPosition_Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPosition_TitleActionPerformed(evt);
            }
        });

        jTextCell_Phone_Number.setBackground(new java.awt.Color(204, 204, 204));
        jTextCell_Phone_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCell_Phone_NumberActionPerformed(evt);
            }
        });

        jTextEmail_Address.setBackground(new java.awt.Color(204, 204, 204));

        jSave.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jSave.setText("SAVE");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Photo:");

        jUpload.setBackground(new java.awt.Color(204, 204, 204));
        jUpload.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jUpload.setText("Upload");
        jUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUploadActionPerformed(evt);
            }
        });

        jDateChooser.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jDateChooser.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpload)
                        .addGap(94, 94, 94)
                        .addComponent(jSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPosition_Title)
                            .addComponent(jTeam_Info)
                            .addComponent(jLevel)
                            .addComponent(jStart_Date)
                            .addComponent(jGender)
                            .addComponent(jAge)
                            .addComponent(jEmployee_ID)
                            .addComponent(jName)
                            .addComponent(jContact_Info))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextTeam_Info, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextGender, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAge, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEmployee_ID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPosition_Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                                    .addComponent(jTextLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCell_Phone_Number)
                                    .addComponent(jEmail_Address))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextCell_Phone_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                    .addComponent(jTextEmail_Address))))))
                .addGap(0, 125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jTitle)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployee_ID)
                    .addComponent(jTextEmployee_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAge)
                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGender)
                    .addComponent(jTextGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStart_Date))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTeam_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTeam_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPosition_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPosition_Title))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jContact_Info))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCell_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCell_Phone_Number))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextEmail_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail_Address))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUpload)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSave)))
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPosition_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPosition_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPosition_TitleActionPerformed

    private void jTextCell_Phone_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCell_Phone_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCell_Phone_NumberActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        JTextField[] VARIABLE_CONSTANTS = {jTextName,jTextEmployee_ID,jTextAge,jTextGender,jTextLevel,
        jTextTeam_Info,jTextPosition_Title,jTextCell_Phone_Number,jTextEmail_Address};
        boolean validated = false;
        for(JTextField field: VARIABLE_CONSTANTS){
            if(!validation(field)){
                validated = false;
                break;
            }
            else{
                validated = true;
               
            }
        }
        
        
        if(validated){
        
        int Age = Integer.parseInt(jTextAge.getText());
        SimpleDateFormat sanju = new SimpleDateFormat("MMM d, y");
        
        historyArrayList.getHistoryArrayList().add(productdetails);
        productdetails.setName(jTextName.getText());
        productdetails.setEmployee_ID(jTextEmployee_ID.getText());
        productdetails.setGender(jTextGender.getText());
        productdetails.setLevel(jTextLevel.getText());
        productdetails.setAge(Age);
        productdetails.setPosition_Title(jTextPosition_Title.getText());
        productdetails.setStart_Date(jDateChooser.getDate());
        productdetails.setTeam_info(jTextTeam_Info.getText());
        productdetails.setPhone_Number(jTextCell_Phone_Number.getText());
        productdetails.setEmail(jTextEmail_Address.getText());
        System.out.println(historyArrayList.getHistoryArrayList().size());
        JOptionPane.showMessageDialog(this, "New Profile added");
        JOptionPane.showMessageDialog(this, "Click 'Create' again to enter a New Employee");
      
        }
        
    }//GEN-LAST:event_jSaveActionPerformed

    private void jUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUploadActionPerformed
        // TODO add your handling code here:
         JFileChooser fileUploader = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG & JPEG Images", "jpg", "jpeg");
        fileUploader.setFileFilter(filter);
        fileUploader.setDialogTitle("Select Your Photo");
        fileUploader.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnval = fileUploader.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION)
        {
            File uploadedFile = fileUploader.getSelectedFile();
            BufferedImage bufferedImageObj;
            try {
                bufferedImageObj = ImageIO.read(uploadedFile);
                ByteArrayOutputStream byteArrayOs = new ByteArrayOutputStream();
                ImageIO.write(bufferedImageObj, "jpg", byteArrayOs);
                byte[] photoBytes = byteArrayOs.toByteArray();
                productdetails.setPhoto(photoBytes);
               // historyArrayList.getHistoryArrayList().add(productdetails);
                JOptionPane.showMessageDialog(fileUploader, "Photo Uploaded");
            } catch(IOException e) {
               e.printStackTrace();
               JOptionPane.showMessageDialog(fileUploader, "Photo not Uploaded");
            }
        }
        
    }//GEN-LAST:event_jUploadActionPerformed
public boolean validation(JComponent input) 
{       Date s = jDateChooser.getDate();
        String x = input.getName();
        String Merror="";
        boolean raiseError = false;
        String tex = ((JTextField) input).getText().trim();
        if (tex == null || tex.isEmpty()) 
        {
            raiseError = true;
            Merror = String.format("Enter a Value. %s cannot be empty", x);
        }
        else if(s == null){
            raiseError = true;
            Merror = String.format("Enter a Value. Start Date cannot be empty");
        }
        
        else
        {
            switch (x) {
                case "Name":
                    if(!tex.matches("^[a-zA-z ,.'-]+$")){
                        /*^[a-zA-z]+$*/
                        raiseError = true;
                        Merror = String.format("Enter correct %s", x);
                    }   break;
                case "Phone_Number":
                    if(!tex.matches("^[0-9]{10}")){
                        raiseError = true;
                        Merror = String.format("Enter correct %s", x);
                    }
                    else{
                    
                    for (ProductDetails productdetails : historyArrayList.getHistoryArrayList())
                  {
                      if (String.valueOf(productdetails.getPhone_Number()).equals(tex))
                  {
                   raiseError = true;
                    Merror = String.format("Phone Number Already exists. Enter a new one", x);
                    break;
                     }
                    }}
                     
                    break;
                case "Employee_ID":
                    for (ProductDetails productdetails : historyArrayList.getHistoryArrayList())
                  {
                   if (String.valueOf(productdetails.getEmployee_ID()).equals(tex))
                  {
                   raiseError = true;
                    Merror = String.format("Employee ID Already exists. Enter a new one", x);
                     }
                    }    break;
                case "Age":
                    if (!tex.matches("^[0-9]{1}|[0-9]{2}|[0-9]{3}"))
                    {
                        raiseError = true;
                        Merror = String.format("Enter correct %s", x);
                    }break;
                case "Email":
                    
                    if(!tex.matches("^(.+)@(.+)$")){
                        raiseError = true;
                        Merror = String.format("Enter correct %s", x);
                    } 
                    else{
                    
                  for (ProductDetails productdetails : historyArrayList.getHistoryArrayList())
                  {
                  if (String.valueOf(productdetails.getEmail()).equals(tex))
                  {
                  raiseError = true;
                  Merror = String.format("Email already Exists. Enter a new one");
                  break;
                  } 
                  } } break;
                   
                default:
                    break;
            }
        }
        if (raiseError){
            JOptionPane.showMessageDialog(this, Merror);
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAge;
    private javax.swing.JLabel jCell_Phone_Number;
    private javax.swing.JLabel jContact_Info;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private javax.swing.JLabel jEmail_Address;
    private javax.swing.JLabel jEmployee_ID;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPosition_Title;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel jStart_Date;
    private javax.swing.JLabel jTeam_Info;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextCell_Phone_Number;
    private javax.swing.JTextField jTextEmail_Address;
    private javax.swing.JTextField jTextEmployee_ID;
    private javax.swing.JTextField jTextGender;
    private javax.swing.JTextField jTextLevel;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPosition_Title;
    private javax.swing.JTextField jTextTeam_Info;
    private javax.swing.JLabel jTitle;
    private javax.swing.JButton jUpload;
    // End of variables declaration//GEN-END:variables
}
