/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.EmployeeData;
import model.ProductDetails;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author sumanayanakonda
 */
public class ViewandDeleteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewandDeleteJPanel
     */
    
    EmployeeData historyArrayList;
    ProductDetails productdetails = new ProductDetails();
    public ViewandDeleteJPanel(EmployeeData historyArrayList) {
        initComponents();
        
       
        this.historyArrayList = historyArrayList;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEmployee_ID = new javax.swing.JLabel();
        jEmail_Address = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jAge = new javax.swing.JLabel();
        jTextEmployee_ID = new javax.swing.JTextField();
        jGender = new javax.swing.JLabel();
        jStart_Date = new javax.swing.JLabel();
        jTextStart_Date = new javax.swing.JTextField();
        jLevel = new javax.swing.JLabel();
        jTextLevel = new javax.swing.JTextField();
        jTeam_Info = new javax.swing.JLabel();
        jTextTeam_Info = new javax.swing.JTextField();
        jPosition_Title = new javax.swing.JLabel();
        jTextPosition_Title = new javax.swing.JTextField();
        jTitle = new javax.swing.JLabel();
        jContact_Info = new javax.swing.JLabel();
        jTextCell_Phone_Number = new javax.swing.JTextField();
        jName = new javax.swing.JLabel();
        jCell_Phone_Number = new javax.swing.JLabel();
        jTextEmail_Address = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jNameSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDelete = new javax.swing.JButton();
        jTextGender = new javax.swing.JTextField();
        jTextAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPhoto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jEmployee_ID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jEmployee_ID.setText("Employee ID:");

        jEmail_Address.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jEmail_Address.setText("Email Address:");

        jTextName.setBackground(new java.awt.Color(204, 204, 204));
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jAge.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jAge.setText("Age:");

        jTextEmployee_ID.setBackground(new java.awt.Color(204, 204, 204));

        jGender.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jGender.setText("Gender:");

        jStart_Date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jStart_Date.setText("Start Date:");

        jTextStart_Date.setBackground(new java.awt.Color(204, 204, 204));

        jLevel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLevel.setText("Level:");

        jTextLevel.setBackground(new java.awt.Color(204, 204, 204));

        jTeam_Info.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTeam_Info.setText("Team Info:");

        jTextTeam_Info.setBackground(new java.awt.Color(204, 204, 204));

        jPosition_Title.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPosition_Title.setText("Position Title:");

        jTextPosition_Title.setBackground(new java.awt.Color(204, 204, 204));
        jTextPosition_Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPosition_TitleActionPerformed(evt);
            }
        });

        jTitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("READ");
        jTitle.setToolTipText("");

        jContact_Info.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jContact_Info.setText("Contact Info:");

        jTextCell_Phone_Number.setBackground(new java.awt.Color(204, 204, 204));
        jTextCell_Phone_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCell_Phone_NumberActionPerformed(evt);
            }
        });

        jName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jName.setText("Name:");

        jCell_Phone_Number.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCell_Phone_Number.setText("Cell Phone Number:");

        jTextEmail_Address.setBackground(new java.awt.Color(204, 204, 204));

        jSearch.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jSearch.setText("SEARCH PROFILE");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jNameSearch.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Enter Phone Number/Employee ID: ");

        jDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jDelete.setText(" DELETE PROFILE");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jTextGender.setBackground(new java.awt.Color(204, 204, 204));

        jTextAge.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("View Image:");

        jPhoto.setBackground(new java.awt.Color(204, 204, 204));
        jPhoto.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jPhoto.setText("Photo");
        jPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(jSearch)
                            .addGap(46, 46, 46)
                            .addComponent(jDelete))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(324, 324, 324)
                            .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPosition_Title)
                                .addComponent(jTeam_Info)
                                .addComponent(jLevel)
                                .addComponent(jStart_Date)
                                .addComponent(jGender)
                                .addComponent(jAge)
                                .addComponent(jEmployee_ID)
                                .addComponent(jName)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jContact_Info))
                                .addComponent(jCell_Phone_Number))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextTeam_Info, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextStart_Date, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextEmployee_ID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextPosition_Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                                        .addComponent(jTextCell_Phone_Number, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextGender)
                                        .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jPhoto))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jEmail_Address)
                        .addGap(18, 18, 18)
                        .addComponent(jTextEmail_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearch)
                    .addComponent(jDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployee_ID)
                    .addComponent(jTextEmployee_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAge)
                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGender)
                    .addComponent(jTextGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStart_Date)
                    .addComponent(jTextStart_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLevel)
                    .addComponent(jTextLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTeam_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTeam_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPosition_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPosition_Title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jContact_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCell_Phone_Number)
                    .addComponent(jTextCell_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail_Address)
                    .addComponent(jTextEmail_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPhoto))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextPosition_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPosition_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPosition_TitleActionPerformed

    private void jTextCell_Phone_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCell_Phone_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCell_Phone_NumberActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        String Name_Searched = jNameSearch.getText();
        search_list(Name_Searched);
        
    }//GEN-LAST:event_jSearchActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        String To_Delete = jNameSearch.getText();
        boolean test = false;
        int i = 0;
        for (ProductDetails productdetails : historyArrayList.getHistoryArrayList())
        {
           if (String.valueOf(productdetails.getPhone_Number()).equals(To_Delete)||String.valueOf(productdetails.getEmployee_ID()).equals(To_Delete))
           {  
        historyArrayList.eraseElement(i);
        test = true;
        jTextName.setText("");
        jTextEmployee_ID.setText("");
        jTextGender.setText("");
        jTextLevel.setText("");
        jTextAge.setText("");
        jTextPosition_Title.setText("");
        jTextStart_Date.setText("");
        jTextTeam_Info.setText("");
        jTextCell_Phone_Number.setText("");
        jTextEmail_Address.setText("");
        JOptionPane.showMessageDialog(this, "Profile Deleted"); 
        break;
           }
        i++;}
        
        if (!test){
          JOptionPane.showMessageDialog(this, "Number Not Found");   
        }
    
    
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhotoActionPerformed
        // TODO add your handling code here:
        
        try{
           ProductDetails pphoto=new ProductDetails();
           for(ProductDetails productdetails:historyArrayList.getHistoryArrayList())
        {
        if(String.valueOf(productdetails.getPhone_Number()).equals(jNameSearch.getText()))
        {
            pphoto=productdetails;
            break;
        }
        }
           BufferedImage photo = ImageIO.read(new ByteArrayInputStream(pphoto.getPhoto()));
            JFrame viewImgFrame = new JFrame();
            ImageIcon icon = new ImageIcon(photo);
            JLabel label = new JLabel(icon);
            viewImgFrame.add(label);
            viewImgFrame.pack();
            viewImgFrame.setVisible(true);
         }
        catch (IOException e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jPhoto, "Error Loading the Image");
        }
    
        
    }//GEN-LAST:event_jPhotoActionPerformed
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAge;
    private javax.swing.JLabel jCell_Phone_Number;
    private javax.swing.JLabel jContact_Info;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jEmail_Address;
    private javax.swing.JLabel jEmployee_ID;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JTextField jNameSearch;
    private javax.swing.JButton jPhoto;
    private javax.swing.JLabel jPosition_Title;
    private javax.swing.JButton jSearch;
    private javax.swing.JLabel jStart_Date;
    private javax.swing.JLabel jTeam_Info;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextCell_Phone_Number;
    private javax.swing.JTextField jTextEmail_Address;
    private javax.swing.JTextField jTextEmployee_ID;
    private javax.swing.JTextField jTextGender;
    private javax.swing.JTextField jTextLevel;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPosition_Title;
    private javax.swing.JTextField jTextStart_Date;
    private javax.swing.JTextField jTextTeam_Info;
    private javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables

private void displayObject(ProductDetails productdetails){
    SimpleDateFormat sanju = new SimpleDateFormat("MMM d, y");
    jTextName.setText(productdetails.getName());
    jTextEmployee_ID.setText(productdetails.getEmployee_ID());
    jTextAge.setText(String.valueOf(productdetails.getAge()));
    jTextGender.setText(productdetails.getGender());
    jTextCell_Phone_Number.setText(productdetails.getPhone_Number());
    jTextEmail_Address.setText(productdetails.getEmail());
    jTextLevel.setText(productdetails.getLevel());
    jTextPosition_Title.setText(productdetails.getPosition_Title());
    jTextStart_Date.setText(sanju.format(productdetails.getStart_Date()));
    jTextTeam_Info.setText(productdetails.getTeam_info());  
    
}

    private void search_list(String a) {
      boolean test = false;
        for (ProductDetails productdetails : historyArrayList.getHistoryArrayList()){
         
           if ((String.valueOf(productdetails.getPhone_Number()).equals(a))||(productdetails.getEmployee_ID().equals(a)))
           {  
    displayObject(productdetails);
    test = true;
    break;
           }
           }
        if(!test){
            
                JOptionPane.showMessageDialog(this, "Number Not Found");
            
        }
      
    }
    
    }
    

            
    




